FROM cgr.dev/chainguard/go:latest AS builder

LABEL org.opencontainers.image.source=https://github.com/chair6/test-go-container-images

WORKDIR /build

COPY ./src/hello/* /build/
RUN go build -o hello hello.go

FROM cgr.dev/chainguard/alpine-base:latest
COPY --from=builder /build/hello /bin/hello
ENTRYPOINT ["/bin/hello"]
