FROM golang:alpine AS builder

LABEL org.opencontainers.image.source=https://github.com/chair6/test-go-container-images

WORKDIR /build

COPY ./src/hello/* /build/
RUN go build -o hello hello.go

FROM scratch
COPY --from=builder /build/hello /bin/hello
ENTRYPOINT ["/bin/hello"]
